services:
  - type: web
    name: credential-vault
    env: python
    buildCommand: ""
    startCommand: gunicorn flask_app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here