services:
  - type: web
    name: credential-vault
    env: python
    plan: free

    buildCommand: |
      apt-get update -y
      apt-get install -y libjpeg-dev zlib1g-dev   # Pillow PNG/JPEG support
      pip install -r requirements.txt

    startCommand: gunicorn flask_app:app

    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        value: your-secret-key-here